# Generated by Django 3.0.8 on 2020-07-05 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CupCake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=70, verbose_name='Название')),
                ('price', models.CharField(blank=True, max_length=25, verbose_name='Цена')),
                ('slug', models.SlugField(blank=True, verbose_name='Артикул')),
                ('body', models.TextField(blank=True, max_length=150, verbose_name='Аннотация')),
                ('drop_body', models.TextField(blank=True, max_length=350, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
            options={
                'verbose_name': 'Капкейк',
                'verbose_name_plural': 'Капкейки',
            },
        ),
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=70, verbose_name='Название')),
                ('price', models.CharField(blank=True, max_length=25, verbose_name='Цена')),
                ('slug', models.SlugField(blank=True, verbose_name='Артикул')),
                ('body', models.TextField(blank=True, max_length=150, verbose_name='Аннотация')),
                ('drop_body', models.TextField(blank=True, max_length=350, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
            options={
                'verbose_name': 'Торт',
                'verbose_name_plural': 'Торты',
            },
        ),
    ]
